services:
  - type: web
    name: calorie-predictor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run calorie.py --server.port $PORT --server.enableCORS false"
